language: php

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm
    - php: 7

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text
